# this is a comment
title: Joshua Hunt
logo: pics/cropped_punk.jpg
description: This is a picture of me
show_downloads: false
google_analytics:
url: https://jhunt7.github.io
theme: jekyll-theme-minimal
